/**
 * @file cli-basic.tests.test.js
 * @description Generated test file from cli-basic.tests.yml.
 * This file contains Jest 'describe' and 'it' blocks based on your YAML structure.
 * Please fill in the actual test logic.
 * @generated by testweaver
 */

describe('Basic flags', () => {
  describe('Help flags', () => {
    it.todo('-h');
    it.todo('--help');
  });

  describe('Version', () => {
    it.todo('-V');
    it.todo('--version');
  });

});

describe('Show descriptions to console', () => {
  describe('Local repo', () => {
    it.todo('Current repo: .');
    it.todo('Repo folder on local machine');
  });

  describe('Remote repos', () => {
    it.todo('From GitHub: ioncakephper/repo-description');
  });

});

describe('Send descriptions to file', () => {
  describe('Local repo', () => {
    it.todo('Current repo: . -o _descriptions.json');
    it.todo('Current repo: . -o _descriptions.json -f json');
    it.todo('Current repo: . -o _descriptions_markdown.md -f markdown');
  });

  describe('Remote repos', () => {
    describe('From GitHub: ioncakephper/repo-description', () => {
      it.todo('https://github.com/ioncakephper/repo-description -o _descriptions.json');
      it.todo('https://github.com/ioncakephper/repo-description -o _descriptions.json -f json');
      it.todo('https://github.com/ioncakephper/repo-description -o _descriptions_markdown.md -f markdown');
    });

  });

});

